### ISSUE TITLE
Very cool

### ISSUE THREAD

**Issue by smdjeff** [slx7R4GDZM/Sine-Toolkit#1]
Didn't see any contact so opened an issue. I found your Sine project while digging around for information on how collision detection worked on the original 6502 Asteroids. I could have used something like this toolkit to design Sega G80 vectors. I ended up writing some python to dump them directly from the ROMs.

https://github.com/smdjeff/sega-g80-vector-homebrew/blob/main/sega-vector-dump.py
https://github.com/smdjeff/sega-g80-vector-diagnostics/blob/main/dump/klingon.gif

**Comment by slx7R4GDZM** [comment]
Yeah, the collision is pretty simple, it's just whether two circles intersect. The complexity is mostly just dealing with the high and low bits due to everything being 8-bit.
Sine's missing a few opcodes compared to DVG because I didn't really need to care about performance and I could just use the framebuffer that we've got now instead of dealing with the program counter stuff.
Seems like there's less discussion on the Sega G80 vectors compared to the Atari DVG.
Neat stuff though.
